version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    volumes:
      - ./configs/monitoring/prometheus.prod.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      rada:
        condition: service_healthy
    restart: unless-stopped
